config/routes.rb
Rails.application.routes.draw do
  #home/root path
  root to: "home#index"
  
  #home pages
  get 'home/index'
  get 'home/about'
  get 'home/scrape'
  get 'home/contact'
  
  #legacy pages
  get 'legacy/one'
  get 'legacy/two'
  get 'legacy/three'

  #other pages
  get 'home/maps'
  
  #redirects
  get '/harmonyrosters', to: redirect('https://docs.google.com/spreadsheets/d/1a6gvHt-BPyViXasGsw6D_abziPXwAvHIJxIbDtcpNJ4/edit?usp=sharing'), :as => :harmonyrosters
  get '/discordrosters', to: redirect('https://docs.google.com/spreadsheets/d/1u3KCN6QmROo4uwPyEd1xa4QD6rbZZqiIyO8Q9yNFq_M/edit?usp=sharing'), :as => :discordrosters
  get '/trancerosters', to: redirect('https://docs.google.com/spreadsheets/d/159P4gIkI3gfzGnmjrFPySIjk2QqUDKmg3d6chUHLStE/edit?usp=sharing'), :as => :trancerosters
  get '/wmsharmonyaurum', to: redirect('https://docs.google.com/spreadsheets/d/1btPcbSt7ZkSIr4n7MeUHhbTbiY6vu99773S_IcVsaKk/edit?usp=sharing'), :as => :wmsharmonyaurum
  get '/wmsharmonyindigo', to: redirect('https://docs.google.com/spreadsheets/d/1oLZzcTzej4rSW2uuJgXS1iSnrY1KNdWK34GnspDjmKE/edit?usp=sharing'), :as => :wmsharmonyindigo
  get '/wmsharmonyelimination', to: redirect('https://docs.google.com/spreadsheets/d/1Q9QjZ3TGS54ePoLn68iV2AVyvpH9uTZZ4DaaNFQYLXc/edit?usp=sharing'), :as => :wmsharmonyelimination
  get '/wmsdiscordaurum', to: redirect('https://docs.google.com/spreadsheets/d/1NVOyhsHBsX-drHD9nMdufKKlFTSZw91fFTpkKpwfoXI/edit?usp=sharing'), :as => :wmsdiscordaurum
  get '/wmsdiscordindigo', to: redirect('https://docs.google.com/spreadsheets/d/1X1bXP87QMTJzA65D7XXib6eI4trtPQnNgsGDNzizK_0/edit?usp=sharing'), :as => :wmsdiscordindigo
  get '/wmsdiscordelimination', to: redirect('https://docs.google.com/spreadsheets/d/1PtgVkQzz5_e-BkfJRUClyhCFnB6S8CnTVBfVVEWR9D4/edit?usp=sharing'), :as => :wmsdiscordelimination
  get '/wmstranceaurum', to: redirect('https://docs.google.com/spreadsheets/d/1yVHVj35j5Sre9XFqCISSh_PK_5Kzf9oRiAhhA3up0bo/edit?usp=sharing'), :as => :wmstranceaurum
  get '/wmstranceindigo', to: redirect('https://docs.google.com/spreadsheets/d/1e3EN4nFV9kF1j8G9zFBkG3aELpuRgM2FQbQ8LKpzDCg/edit?usp=sharing'), :as => :wmstranceindigo
  get '/wmstranceelimination', to: redirect('https://docs.google.com/spreadsheets/d/1fXpsg3Ks6bYxZFeVS9nX9XonIeV3KkeirybwUnLn_bg/edit?usp=sharing'), :as => :wmstranceelimination
  get '/harmonyschedule', to: redirect('https://www.toornament.com/en_US/tournaments/4809730653463879680/matches/schedule'), :as => :harmonyschedule
  get '/discordschedule', to: redirect('https://www.toornament.com/en_US/tournaments/4809775329813782528/matches/schedule'), :as => :discordschedule
  get '/tranceschedule', to: redirect('https://www.toornament.com/en_US/tournaments/4809776538701357056/matches/schedule'), :as => :tranceschedule
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def about
  end

  def contact
  end

  def maps
  end
end

app/controllers/legacy_controller.rb
class LegacyController < ApplicationController
  def one
  end

  def two
  end

  def three
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/_contact.html.erb
<div class="card text-center team-card-bg" style="margin-top: 80px;margin-bottom: 20px;">
  <div class="card-body">
    <p style="text-align: left;">
      For further information please join our discord server <a href="https://discord.gg/JCUxVh9">here</a> and reach out to us directly.
      <br/><br/>
    <b>Cavalier</b>  – Commissioner –  Art & Branding Manager - cavalier@owtranquility.com<br/>
    <b>SkifreeYeti</b> – Transcendence Tier Director – Content Creation Manager - Iris Podcast Lead<br/>
    <b>Crispy</b> - Discord Tier Director - Social Media Manager<br/>
    <b>Thuggington</b> – Harmony Tier Director<br/>
    <b>Booth</b> – Twitch Manager<br/>
    <b>NPC</b> - Community Officer<br/>
    <b>Bethcon2</b> - Community Officer<br/>
    <br/>
    <i>Additional Moderation Team Members</i>
    <br/>
    <b>Triage3</b> - Moderator – Community Liaison<br/>
    <b>Captjack87</b> - Moderator - Community Liaison<br/>
    <b>Sneakykittens</b> - Moderator - Community Liaison - Asst. Tier Director<br/>
    <b>Chimanzy</b> - Moderator - Asst. Tier Director<br/>
    <b>Impurse</b> - Moderator - Asst. Tier Director<br/>
    <b>RaceFPV</b> - Webcode<br/>
</p>
  </div>
</div>

app/views/home/_welcome.html.erb
<div class="card text-center team-card-bg" style="margin-top: 80px;margin-bottom: 20px;">
  <div class="card-body">
    <%= image_tag("2021TranqBadge.png", width: "70%", alt: "tranq banner") %>
    <hr/>
    <p style="text-align: left;">
    Welcome to the Overwatch Tranquility Community. This community is intended to aid in the growth of players and their development in the game of Overwatch. It was first conceived as a casual intramural level tournament but has evolved into a developmental community helping players across multiple skill tiers in a season style format.
    <br/><br/>
    With that being said, Overwatch Tranquility is a well-organized community and will take the structure, branding, production and operation seriously. It’s a community that is meant to be fun and drama free, but that only works if everyone participates and follows the developed guidelines.
    <br/><br/>
    After six successful seasons we are set to kick off Season 7 the week of August 16, 2021 with 72 total teams across three skill tiers.
    <br/><br/>
    Harmony Tier (2000-3000 w/ 2650 SR avg)
    Discord Tier (2800-3500 w/ 3200 SR avg)
    Transcendence Tier (3300-4000 w/ 3750 SR avg)
    <br/><br/>
    The OWTC is open to all players in the Gold (2000 SR) to Masters (4000 SR) range, and it is meant to be an inclusive space to help build a community of competition and friendship.
    <br/><br/>
    I am looking forward to working with all of you to continue this community's success for years to come!
    <br/><br/>
    Thank You,
    <br/>
    Cavalier
    <br/>
    Commissioner
</p>
<i>-- Season 7 starts the week of August 16th, 2021, <a href="https://www.twitch.tv/owtranquility" style="color: #CC922E;">Watch the latest matches on twitch.tv</a> --</i>
  </div>
</div>

app/views/home/contact.html.erb
<div style="background-image: url(<%= asset_path 'contactBackdrop.png' %>); background-size: cover; background-repeat: no-repeat; background-position: cover; width: 100vw; height: 100vh;" >
<div class="container">
<div class="row justify-content-md-center align-items-center">
<div class="col-sm-8">
<%= render 'home/contact'%>
</div>
</div>
</div>
</div>

app/views/home/index.html.erb
<div style="background-image: url(<%= asset_path 'mainpageBackdrop.png' %>); background-size: cover; background-repeat: no-repeat; background-position: cover; width: 100vw; height: 100vh;" >
<div class="container">
<div class="row justify-content-md-center align-items-center">
<div class="col-sm-10">
<%= render 'home/welcome'%>
</div>
</div>
</div>
</div>

app/views/home/maps.html.erb
<% Dir.glob('app/assets/images/maps/*').map do |path| %>
    <%= link_to(image_tag("maps/#{ File.basename(path) }", style: 'max-width: 40%;'), image_path( "maps/#{ File.basename(path) }")) %>
<% end.reduce(&:+) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Overwatch Tranquility</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('tranq2020favicon.png') %>
  </head>

  <body class="text-center">
    <div id="wrap">
      <%= render 'shared/nav' %>
      <div id="main" class="clear-top">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p>Crafted with love for Overwatch Tranquility by <a href="https://github.com/racefpv" class="footer-link">RaceFPV</a></p>
  </div>
</footer>

app/views/shared/_nav.html.erb
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <%= link_to(root_path, class: "navbar-brand") do %>
      <%= image_tag 'tranq2020favicon.png', class: 'd-inline-block align-top', style: 'width: 30px; height: 30px;' %>
      Overwatch Tranquility
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Rosters
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to('Harmony Tier 2000 – 3000 SR (2650 SR Average)', harmonyrosters_path, class: "dropdown-item") %>
            <%= link_to('Discord Tier 2800 – 3500 SR (3200 SR Average)', discordrosters_path, class: "dropdown-item") %>
            <%= link_to('Transcendence Tier 3300 - 4000 SR (3750 SR Average)', trancerosters_path, class: "dropdown-item") %>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Matches
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to('Harmony Tier Aurum', wmsharmonyaurum_path, class: "dropdown-item", :target => "_blank") %>
            <%= link_to('Harmony Tier Indigo', wmsharmonyindigo_path, class: "dropdown-item", :target => "_blank") %>
            <%= link_to('Harmony Tier Elimination', wmsharmonyelimination_path, class: "dropdown-item", :target => "_blank") %>
            <%= link_to('Discord Tier Aurum', wmsdiscordaurum_path, class: "dropdown-item", :target => "_blank") %>
            <%= link_to('Discord Tier Indigo', wmsdiscordindigo_path, class: "dropdown-item", :target => "_blank") %>
            <%= link_to('Discord Tier Elimination', wmsdiscordelimination_path, class: "dropdown-item", :target => "_blank") %>
            <%= link_to('Transcendence Tier Aurum', wmstranceaurum_path, class: "dropdown-item", :target => "_blank") %>
            <%= link_to('Transcendence Tier Indigo', wmstranceindigo_path, class: "dropdown-item", :target => "_blank") %>
            <%= link_to('Transcendence Tier Elimination', wmstranceelimination_path, class: "dropdown-item", :target => "_blank") %>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Schedule
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to('Harmony Tier', harmonyschedule_path, class: "dropdown-item", :target => "_blank") %>
            <%= link_to('Discord Tier', discordschedule_path, class: "dropdown-item", :target => "_blank") %>
            <%= link_to('Transcendence Tier', tranceschedule_path, class: "dropdown-item", :target => "_blank") %>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Store
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to('Apparel', "https://shop.spreadshirt.com/owtranquility/", class: "dropdown-item", :target => "_blank") %>
            <%= link_to('Jerseys', "https://shop.spreadshirt.com/owtranquilityjerseys", class: "dropdown-item", :target => "_blank") %>
            <%= link_to('Retired Jerseys', "https://shop.spreadshirt.com/owtranquilityretired/", class: "dropdown-item", :target => "_blank") %>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Social Media
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to('Twitch', "https://www.twitch.tv/owtranquility", class: "dropdown-item", :target => "_blank") %>
            <%= link_to('Twitter', "https://twitter.com/owtranquility", class: "dropdown-item", :target => "_blank") %>
            <%= link_to('Youtube', "http://www.youtube.com/c/owtranquility", class: "dropdown-item", :target => "_blank") %>
            <%= link_to('Discord', "http://www.discord.io/owtranquility", class: "dropdown-item", :target => "_blank") %>
            <%= link_to('Facebook', "http://www.facebook.com/owtranquility", class: "dropdown-item", :target => "_blank") %>
            <%= link_to('Maps', home_maps_path, class: "dropdown-item") %>
          </div>
        </li>
        <li class="nav-item">
          <%= link_to('Contact', home_contact_path, class: "nav-link") %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/tier/_card_template.html.erb
  <div class="col-md-6">
    <div class="card flex-md-row mb-4 box-shadow h-md-250">
      <div class="card-body d-flex flex-column align-items-start">
        <h3 class="mb-0">
          <a class="text-dark" href="#">Eclipse</a>
        </h3>
        <div class="mb-1 text-muted">Average SR: 3500</div>
        <hr style="margin-top: 10px; margin-bottom: 5px;">
        <p class="card-text mb-auto">Something interesting about the team goes here, or maybe the team members.....</p>
        <%= link_to 'Team Page', team_eclipse_path, style: 'color: #000;' %>
      </div>
      <img class="card-img-right flex-auto d-none d-md-block" style="max-width: 200px;" src="<%= asset_path 'season_three_teams/discord/eclipse_too.png' %>">
    </div>
  </div>

app/views/tier/_revival.html.erb
<div class="col-md-6">
    <div class="card flex-md-row mb-4 box-shadow h-md-250">
      <div class="card-body d-flex flex-column align-items-start">
        <h3 class="mb-0">
          <a class="text-dark" href="#">Karma</a>
        </h3>
        <div class="mb-1 text-muted">Average SR: 2500</div>
        <hr style="margin-top: 10px; margin-bottom: 5px;">
        <p class="card-text mb-auto">Something interesting about the team goes here, or maybe the team members.....</p>
        <%= link_to 'Team Page', team_karma_path, style: 'color: #000;' %>
      </div>
      <img class="card-img-right flex-auto d-none d-md-block" style="max-width: 200px;" src="<%= asset_path 'season_three_teams/harmony/karma_too.png' %>">
    </div>
  </div>

app/views/tier/cards/discord/_majesty_ruby.html.erb
<% team = Team.find_by_name("Majesty Ruby") %>
<div class="card text-center team-card-size">
  <img class="card-img-top" src="<%= asset_path 'season_three_teams/discord/majesty_too.png' %>">
  <div class="card-body-nopad card-body">
    <h3 class="mb-0 text-dark">
      <%= team.name %>
    </h3>
    <h5 class="text-dark">Total members: <%= team.player.count %></h5>
    <div class="text-muted">AVG Team SR: <%= team.sr %></div>
    <br/>
    <div class="card-footer card-footer-nopad">
      <%= link_to team_majesty_ruby_path, class: 'btn btn-block btn-light team-card-btn' do %>
        View Roster <i class="fas fa-angle-down"></i>
      <% end %>
    </div>
  </div>
</div>

app/views/tier/cards/discord/_snowday.html.erb
<% team = Team.find_by_name("Snowday") %>
<div class="card text-center team-card-size">
  <img class="card-img-top" src="<%= asset_path 'season_three_teams/discord/snowday_too.png' %>">
  <div class="card-body-nopad card-body">
    <h3 class="mb-0 text-dark">
      <%= team.name %>
    </h3>
    <h5 class="text-dark">Total members: <%= team.player.count %></h5>
    <div class="text-muted">AVG Team SR: <%= team.sr %></div>
    <br/>
    <div class="card-footer card-footer-nopad">
      <%= link_to team_snowday_path, class: 'btn btn-block btn-light team-card-btn' do %>
        View Roster <i class="fas fa-angle-down"></i>
      <% end %>
    </div>
  </div>
</div>

app/views/tier/cards/harmony/_cherry_bomb.html.erb
  <div class="col-md-6">
    <div class="card flex-md-row mb-4 box-shadow h-md-250">
      <div class="card-body d-flex flex-column align-items-start">
        <h3 class="mb-0">
          <a class="text-dark" href="#">Cherry Bomb</a>
        </h3>
        <div class="mb-1 text-muted">Average SR: <%= Team.find_by_name("Cherry Bomb").sr %></div>
        <hr style="margin-top: 10px; margin-bottom: 5px;">
        <p class="card-text mb-auto">Something interesting about the team goes here, or maybe the team members.....</p>
        <%= link_to 'Team Page', team_cherry_bomb_path, style: 'color: #000;' %>
      </div>
      <img class="card-img-right flex-auto d-none d-md-block" style="max-width: 200px;" src="<%= asset_path 'owt_logo_small.png' %>">
    </div>
  </div>

app/views/tier/cards/harmony/_gravity.html.erb
<% team = Team.find_by_name("Gravity") %>
<div class="card text-center team-card-size">
  <img class="card-img-top" src="<%= asset_path 'season_three_teams/harmony/gravity_too.png' %>">
  <div class="card-body-nopad card-body">
    <h3 class="mb-0 text-dark">
      <%= team.name %>
    </h3>
    <h5 class="text-dark">Total members: <%= team.player.count %></h5>
    <div class="text-muted">AVG Team SR: <%= team.sr %></div>
    <br/>
    <div class="card-footer card-footer-nopad">
      <%= link_to team_gravity_path, class: 'btn btn-block btn-light team-card-btn' do %>
        View Roster <i class="fas fa-angle-down"></i>
      <% end %>
    </div>
  </div>
</div>

app/views/tier/cards/harmony/_undead_battery.html.erb
  <div class="col-md-6">
    <div class="card flex-md-row mb-4 box-shadow h-md-250">
      <div class="card-body d-flex flex-column align-items-start">
        <h3 class="mb-0">
          <a class="text-dark" href="#">Unded Battery</a>
        </h3>
        <div class="mb-1 text-muted">Average SR: <%= Team.find_by_name("Unded Battery").sr %></div>
        <hr style="margin-top: 10px; margin-bottom: 5px;">
        <p class="card-text mb-auto">Something interesting about the team goes here, or maybe the team members.....</p>
        <%= link_to 'Team Page', team_undead_battery_path, style: 'color: #000;' %>
      </div>
      <img class="card-img-right flex-auto d-none d-md-block" style="max-width: 200px;" src="<%= asset_path 'owt_logo_small.png' %>">
    </div>
  </div>